CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
WINDOW_NAME = "Rescue Vision"
SIDE_COLOR = "red"
USE_YOLO_DETECTOR = False
YOLO_MODEL_PATH = "models/best.pt"
YOLO_INPUT_SIZE = 640
YOLO_FRAME_INTERVAL = 3
YOLO_SEARCH_ONLY = True

SERIAL_PORT = "COM3"
SERIAL_BAUDRATE = 115200
SERIAL_ENABLED = False
SERIAL_TIMEOUT = 0.1
SERIAL_REPEAT_INTERVAL_SEC = 0.2

BINARIZE_THRESHOLD = 140
MIN_BRIGHTNESS = 45
MIN_LAPLACIAN_VARIANCE = 80

FORWARD_RATIO = 0.45
TURN_RATIO = 0.35

COLOR_MIN_AREA = 400
TARGET_CENTER_TOLERANCE = 20
TARGET_STOP_AREA = 18000
TARGET_LOST_TOLERANCE_FRAMES = 3
ENABLE_LOAD_REVIEW = False
ENABLE_REJECT_ITEM = False

ENABLE_CLAHE = True
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID_SIZE = 8
GAUSSIAN_KERNEL_SIZE = 5
